### PR TITLE
Improve appearance speed

### PR DESCRIPTION
**Pull request by YuyaKobayashi**
I created pipelined-version of this APP.

### CODE REVIEW

**Comment by longphamthai** [comment]
I am compiling and got error:
depthMap_pipelined.cpp:46:10: fatal error: util_time.h: No such file or directory
 #include "util_time.h"
          ^~~~~~~~~~~~~
compilation terminated.
I couldn't find util_time.h.

**Comment by YuyaKobayashi** [comment]
Please update dv-sdk/application to latest `master` branch

**Comment by longphamthai** [comment]
I think I am using the latest master branch, I think util_time.h should be in application/common, right ? , but I could not find it.

**Comment by YuyaKobayashi** [comment]
That header should be in application/common/include.
At least, you can find the file in Github (https://github.com/DigitalMediaProfessionals/application/blob/master/common/include/util_time.h).
So the file must exist.

**Review by longphamthai — COMMENTED** [review]
Makefile, line 22, please remove ")" after $(GPP).

**Pull request merged**
